### ISSUE TITLE
Apt key for Debian Package is expiring on 16.02.2024

### ISSUE THREAD

**Issue by michizubi-SRF** [oerdnj/deb.sury.org#2074]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
Apt key for the Debian package is expiring on 16.02.2024, see the following output:
```
pub   rsa3072 2019-03-18 [SC] [expires: 2026-02-28]
      1505 8500 A023 5D97 F5D1  0063 B188 E2B6 95BD 4743
uid           [ unknown] DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
sub   rsa3072 2019-03-18 [E] [expires: 2024-02-16]
```

**To Reproduce**
1. wget -q https://packages.sury.org/php/apt.gpg -O- | apt-key add -
2. apt-key list 95BD4743

**Your understanding of what is happening**
The key should be updated to extend expiration

**What steps did you take to resolve issue yourself before reporting it here**
See section "To Reproduce"

**Expected behavior**
Key is not expiring in the next 2 weeks

**Distribution (please complete the following information):**
 - OS: Debian
 - Architecture: amd64
 - Repository:  packages.sury.org

**Comment by oerdnj** [comment]
Could you try installing `debsuryorg-archive-keyring` package by hand for now?

I'll automate it later, but I need more people to confirm that installing that package works fine.

**Comment by michizubi-SRF** [comment]
The key is used on a lot of machines.
I'd rather not install that manually on all of them :)

**Comment by oerdnj** [comment]
> The key is used on a lot of machines. I'd rather not install that manually on all of them :)

And I rather not break "a lot of machines" by automating something that will then need manual intervention, so I need confirmation that: `apt install debsuryorg-archive-keyring` works as expected.

**Comment by rfay** [comment]
@oerdnj is `apt install debsuryorg-archive-keyring` the new official technique? I don't see it showing up in https://packages.sury.org/php/README.txt

We'll need to do a release of DDEV so people will have the new key using the official technique, and it sounds like all apt updates will be broken before that?

Please give the full new suggested technique. Right now my testing is blocked by the intermittent
* https://github.com/oerdnj/deb.sury.org/issues/2046

which is happening consistently right now. I'm absolutely not sure where that comes from and when it happens.

**Comment by oerdnj** [comment]
I am not sure yet about the bootstrapping. The `apt.gpg` will still stay in the place. But I need a method to automatically update the keys.

**Comment by rfay** [comment]
I guess the primary request in this issue is to update the apt.gpg ASAP, that alone would solve things for me. 

`apt install debsuryorg-archive-keyring` works for me, but it may only be working after having installed the apt.gpg, and so that seems like a possible chicken-and-egg scenario? I'll test any from-scratch install that you propose.

```
/etc/apt/trusted.gpg.d/debsuryorg-archive.gpg
---------------------------------------------
pub   rsa3072 2019-03-18 [SC] [expires: 2026-02-04]
      1505 8500 A023 5D97 F5D1  0063 B188 E2B6 95BD 4743
uid           [ unknown] DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
sub   rsa3072 2019-03-18 [E] [expires: 2026-02-04]
```

**Comment by oerdnj** [comment]
I’ll probably upload the keyring package to the repository root and update the instructions to install the deb by hand first.

I’ll keep the apt.gpg for the next 2 years.

**Comment by rfay** [comment]
I see that the apt key has been updated, thank you very much.

Initial situation:
```
gpg --list-options show-sig-expire deb.sury.org-php.gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa3072 2019-03-18 [SC] [expires: 2024-02-16]
      15058500A0235D97F5D10063B188E2B695BD4743
uid           DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
sub   rsa3072 2019-03-18 [E] [expires: 2024-02-16]
```

After `curl -sSLo /usr/share/keyrings/deb.sury.org-php.gpg https://packages.sury.org/php/apt.gpg`

```
gpg --list-options show-sig-expire deb.sury.org-php.gpg
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa3072 2019-03-18 [SC] [expires: 2026-02-04]
      15058500A0235D97F5D10063B188E2B695BD4743
uid           DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
sub   rsa3072 2019-03-18 [E] [expires: 2026-02-04]
```

**Comment by bcremer** [comment]
Can confirm that installing `debsuryorg-archive-keyring` pulled the latest keyring versions:

```
$ ls -lha /usr/share/keyrings/deb.sury.org-*
-rw-r--r-- 1 root root 1,8K Feb  5 16:20 /usr/share/keyrings/deb.sury.org-apache2.gpg
-rw-r--r-- 1 root root 1,8K Feb  5 16:20 /usr/share/keyrings/deb.sury.org-bind-dev.gpg
-rw-r--r-- 1 root root 1,8K Feb  5 16:20 /usr/share/keyrings/deb.sury.org-bind-esv.gpg
-rw-r--r-- 1 root root 1,8K Feb  5 16:20 /usr/share/keyrings/deb.sury.org-bind.gpg
-rw-r--r-- 1 root root 1,8K Feb  5 16:20 /usr/share/keyrings/deb.sury.org-nginx.gpg
-rw-r--r-- 1 root root 1,8K Feb  5 16:20 /usr/share/keyrings/deb.sury.org-nginx-mainline.gpg
-rw-r--r-- 1 root root 1,8K Feb  5 16:20 /usr/share/keyrings/deb.sury.org-php.gpg

$ gpg --list-options show-sig-expire  /usr/share/keyrings/deb.sury.org-php.gpg
pub   rsa3072 2019-03-18 [SC] [expires: 2026-02-04]
      15058500A0235D97F5D10063B188E2B695BD4743
uid           DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
sub   rsa3072 2019-03-18 [E] [expires: 2026-02-04]
```

**Comment by michizubi-SRF** [comment]
Thanks a lot for updating the key.
This solves the issue for me for the moment.

**Comment by brenc** [comment]
Just added this to our build. All good. 👍

For reference, the full URL is `https://packages.sury.org/debsuryorg-archive-keyring.deb`. Here are my Ansible plays for this:

```yaml
- name: apt | Add the deb.sury.org key(s) and repo
  tags: apt
  block:
    - name: apt | Remove old key
      ansible.builtin.file:
        path: /usr/share/keyrings/deb.sury.org-php.gpg
        state: absent

    - name: apt | Install the debsuryorg-archive-keyring.deb package
      ansible.builtin.apt:
        deb: https://packages.sury.org/debsuryorg-archive-keyring.deb

    - name: apt | Remove the old Sury PHP repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main
        state: absent

    - name: apt | Add Sury PHP repo
      ansible.builtin.apt_repository:
        repo: deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main
        state: present

# Packages are now available to install.
```

@michizubi-SRF check out Ansible. Super helpful for stuff like this.
