### ISSUE TITLE
[meta] Dashboard

### ISSUE THREAD

**Issue by oerdnj** [oerdnj/deb.sury.org#241]
Since my collection of packages has grown to quite a big number, I am seeking someone with tad bit of spare time who would write something like this:

https://www.0d.be/debian/debian-gnome-3.16-status.html
or
https://udd.debian.org/dmd/?email1=ondrej%40debian.org&nouploader1=on&email2=&email3=&packages=&ignpackages=&format=html#todo

It should support:

* uscan
* PECL
* git and git tags
* tracker.debian.org
* PPA
* arbitrary Debian repository

Then I would have a definition file in some human readable/editable form (CSV, JSON, YAML) and the script would output differences between versions (similar to Debian GNOME status page).

Something like this:
```
php7.0:
# arbitrary_label: <URL> or other identifier
  upstream: uscan:php7.0
  debian: debian:php7.0
  ppa: ppa:ondrej/php/
  dpa: deb https://packages.sury.org/php/
  gbp: git://anonscm.debian.org/pkg-php/php.git?branch=master-7.0
```

And this would turn into one line with version differences.

**Comment by robfrawley** [comment]
Can you write-up a short collection about the new build procedure you've mentioned that makes custom packages based on your sources extremely easy to install?

An what's your time-frame for this?

**Comment by oerdnj** [comment]
@robfrawley not really related to this bug, but it's quite simple:

- change the source package name in `d/changelog`
- regenerate d/control by running `debian/rules debian/control`
- drop your modifications in d/rules.d/ (I merged ZTS support into main master-7.0
- rebuild the package

If you want the extras you need to modify source.lintian-overrides and gbp.conf (and for zts also the phpapi)
http://anonscm.debian.org/cgit/pkg-php/php.git/diff/?h=master-7.0-zts~&id2=master-7.0

JFTR there's ZTS repository located at: ppa:ondrej/php-zts (just PHP 7.0 and it's failing to build atm, but it looks like I just lost a bit of the previous patch I had there, because I remember fixing this).

For the Dashboard/Monitor - there's really no timeframe, but there's lot of packages to monitor for new upstream and Debian versions, and dashboard where I could quickly look (or even fire-up some automated builds) would be tremendous help.

**Comment by robfrawley** [comment]
@oerdnj I somehow missed the GitHub notification that you replied to this. Thanks for that! I noticed you had setup the PPA with ZTS, which is great, I just need to package a bunch of the additional extensions against the ZTS API as well. Anyway, after looking through the package source and the information you gave, it should be easy. Much appreciated.

As for the dashboard, I'll see if I can't cobble something together. You have any objection to Silex (or possibly Symfony) as the backbone?

**Comment by oerdnj** [comment]
@robfrawley The ZTS build is broken right now (something with the wrong directories suffixed '-zts' vs '') and I haven't had time to properly look into that (it should be easy to fix, but it takes ages to build). You can look at ppa:ondrej/php-zts for current failing build logs.

I don't care about the backend, the less effort anybody spents with that the better. Thanks.

**Comment by robfrawley** [comment]
@oerdnj: Can you give me a brief idea of how you'd like automated builds to be kicked off, as well as anything specific to your workflow in this regard that would be important for me to know in order to implement such a feature in the dashboard

**Comment by oerdnj** [comment]
@robfrawley Anything I can easily download with cron and parse with shell. So given the input:
```
php7.0:
# arbitrary_label: <URL> or other identifier
  upstream: uscan:php7.0
  debian: debian:php7.0
  ppa: ppa:ondrej/php/
  dpa: deb https://packages.sury.org/php/
  gbp: git://anonscm.debian.org/pkg-php/php.git?branch=master-7.0
```

The output:
```
php7.0:
  upstream: 7.0.4
  debian: 7.0.3-10
  ppa: [ 7.0.3-11+deb.sury.org+xenial-1, 7.0.3-11+deb.sury.org+trusty-1, ... ] 
  dpa: 7.0.3-11~bpo80+1
  gbp: 7.0.4-11
```
would be fine.

**Comment by szepeviktor** [comment]
> https://www.0d.be/debian/debian-gnome-3.16-status.html

There's a link on this page: [generation script](http://people.debian.org/~fpeters/dgs.py)
It could be a base for the solution.

**Comment by christophlehmann** [comment]
Hi @oerdnj,

i investigated some time in writing the version crawler and it's mostly finished

```yaml
sources:
  dpa:
   releases:
     - jessie
     - stretch

packages:

  php7.0:
    #arbitrary_label: <URL> or other identifier
    #upstream: uscan:php7.0

    git:
      url: https://github.com/php/php-src.git
      tagRegex: 'php-7.0.[0-9]*'

    debian:
      name: php7.0

    ppa:
      url: https://launchpad.net/~ondrej/+archive/ubuntu/php
      name: php7.0

    dpa:
      url: https://packages.sury.org/php
      name: php7.0

  php-xdebug:

    pecl:
     name: xdebug

    dpa:
      url: https://packages.sury.org/php
      name: php-xdebug
```

Output:

```yaml
➜  versions  php run.php
sh: pecl: command not found
php7.0:
    git: [php-7.0.27]
    debian: { buster: [7.0.26-1], sid: [7.0.26-1, 7.0.14-2], stretch: [7.0.19-1] }
    ppa: [7.0.26-2+ubuntu17.10.1+deb.sury.org+2, 7.0.26-2+ubuntu17.04.1+deb.sury.org+2, 7.0.26-2+ubuntu16.04.1+deb.sury.org+2, 7.0.26-2+ubuntu14.04.1+deb.sury.org+2]
    dpa: [7.0.26-2+0~20171207160618.11+jessie~1.gbpe286d4, 7.0.26-2+0~20171207160754.11+stretch~1.gbpe286d4]
php-xdebug:
    pecl: {  }
    dpa: [2.5.5-1+0~20170628201550.1+jessie~1.gbp5a1f48, 2.5.5-1+0~20170628201539.1+stretch~1.gbp5a1f48]
```

Outstanding is `upstream`. Comments til now? You can assign me
